export const ROUTES = {
  home: "/",
  experiences: "/experiences",
  games: "/games",
  scrapbook: "/experiences/scrapbook",
  scrapbookBuild: "/scrapbook/build",
  memoryJar: "/experiences/memory-jar",
  memoryJarBuild: "/memory-jar/build",
  memoryPages: "/experiences/memory-pages",
  memoryPagesBuild: "/memory-pages/build",
  constellation: "/experiences/constellation",
  constellationBuild: "/constellation/build",
  memoryCity: "/experiences/memory-city",
  memoryCityBuild: "/memory-city/build",
  chocolateBouquet: "/experiences/chocolate-bouquet",
  chocolateBouquetBuild: "/chocolate-bouquet/build",
  memoryLantern: "/experiences/memory-lantern",
  memoryLanternBuild: "/memory-lantern/build",
  ourPlaces: "/experiences/our-places",
  ludo: "/experiences/ludo",
  ludoBuild: "/ludo/build",
  whackAMole: "/experiences/whack-a-mole",
  whackAMoleBuild: "/whack-a-mole/build",
  flames: "/experiences/flames",
  flamesBuild: "/flames/build",
  loveCalculator: "/experiences/love-calculator",
  loveCalculatorBuild: "/love-calculator/build",
  foldedNote: "/experiences/folded-note",
  foldedNoteBuild: "/folded-note/build",
  thisOrThat: "/experiences/this-or-that",
  thisOrThatBuild: "/this-or-that/build",
  deluluMeter: "/experiences/delulu-meter",
  deluluMeterBuild: "/delulu-meter/build",
  countdown: "/experiences/countdown",
  countdownBuild: "/countdown/build",
  proposal: "/experiences/proposal",
  proposalBuild: "/proposal/build",
  dateAsk: "/experiences/date-ask",
  dateAskBuild: "/date-ask/build",
  mirrorMatch: "/experiences/mirror-match",
  mirrorMatchBuild: "/mirror-match/build",
  mirrorMatchResults: "/mirror-match/results",
  redZone: "/red-zone",
  desireDeck: "/experiences/desire-deck",
  desireDeckBuild: "/desire-deck/build",
  desireMatcher: "/experiences/desire-matcher",
  desireMatcherBuild: "/desire-matcher/build",
  desireMatcherResults: "/desire-matcher/results",
  diceOfDesire: "/experiences/dice-of-desire",
  diceOfDesireBuild: "/dice-of-desire/build",
  loveCoupons: "/experiences/love-coupons",
  loveCouponsBuild: "/love-coupons/build",
  loveCouponsRedemptions: "/love-coupons/redemptions",
  naughtySpins: "/experiences/naughty-spins",
  naughtySpinsBuild: "/naughty-spins/build",
  snakesAndLovers: "/experiences/snakes-and-lovers",
  snakesAndLoversBuild: "/snakes-and-lovers/build",
  spotifyPlaque: "/experiences/spotify-plaque",
  spotifyPlaqueBuild: "/spotify-plaque/build",
  stringFrame: "/experiences/string-frame",
  stringFrameBuild: "/string-frame/build",
  timelessTreasure: "/experiences/timeless-treasure",
  timelessTreasureBuild: "/timeless-treasure/build",
  timeCapsule: "/experiences/time-capsule",
  timeCapsuleBuild: "/time-capsule/build",
  twentyFourReasons: "/experiences/twenty-four-reasons",
  twentyFourReasonsBuild: "/twenty-four-reasons/build",
  relationshipCalendar: "/experiences/relationship-calendar",
  relationshipCalendarBuild: "/relationship-calendar/build",
  gifts: "/gifts",
  giftOrders: "/gifts/orders",
  giftWishlist: "/gifts/wishlist",
  storefront: "/shop",
  checkout: "/checkout",
  pricing: "/pricing",
  about: "/about",
  blog: "/blog",
  terms: "/terms",
  privacy: "/privacy",
  refund: "/refund",
  feedback: "/feedback",
  /** Standalone “tell us what you were hoping to find” form. */
  ideas: "/ideas",
  recommend: "/recommend",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  memories: "/dashboard/memories",
  /** Public story for Memory Bank. The private bank stays at `memories`. */
  memoryBankStory: "/memory-bank",
  /** Public story for Kynd. The private collection stays at `kynd`. */
  kyndStory: "/kynd",
  kynd: "/dashboard/kynd",
  kyndAsk: "/dashboard/kynd/ask",
  kyndPerson: (id: string) => `/dashboard/kynd/${id}`,
  kyndPersonAsk: (id: string) => `/dashboard/kynd/${id}/ask`,
  memoryHomes: "/dashboard/memories/homes",
  memoryTrash: "/dashboard/memories/trash",
  memoryCircle: (id: string) => `/dashboard/memories/${id}`,
  settings: "/dashboard/settings",
  billing: "/dashboard/billing",
  referrals: "/dashboard/referrals",
  shop: "/dashboard/shop",
  shopProducts: "/dashboard/shop/products",
  shopProductNew: "/dashboard/shop/products/new",
  shopOrders: "/dashboard/shop/orders",
  shopExpenses: "/dashboard/shop/expenses",
  shopReports: "/dashboard/shop/reports",
  shopSettings: "/dashboard/shop/settings",
  admin: "/admin",
  /** Fullscreen marketing demo that mirrors the published public viewer look. */
  experiencePreview: (slug: string) => `/preview/${slug}`,
} as const;

// Marketing/demo surfaces anyone can see. Builder routes (`/*/build`) are
// intentionally NOT here — customising anything requires login, enforced in
// proxy.ts via isBuilderPath().
export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.memoryBankStory,
  ROUTES.kyndStory,
  ROUTES.experiences,
  ROUTES.games,
  ROUTES.feedback,
  ROUTES.ideas,
  ROUTES.recommend,
  ROUTES.scrapbook,
  ROUTES.memoryJar,
  ROUTES.memoryPages,
  ROUTES.constellation,
  ROUTES.memoryCity,
  ROUTES.chocolateBouquet,
  ROUTES.memoryLantern,
  ROUTES.ourPlaces,
  ROUTES.ludo,
  ROUTES.whackAMole,
  ROUTES.flames,
  ROUTES.loveCalculator,
  ROUTES.foldedNote,
  ROUTES.thisOrThat,
  ROUTES.deluluMeter,
  ROUTES.countdown,
  ROUTES.proposal,
  ROUTES.dateAsk,
  ROUTES.mirrorMatch,
  ROUTES.redZone,
  ROUTES.desireDeck,
  ROUTES.desireMatcher,
  ROUTES.diceOfDesire,
  ROUTES.loveCoupons,
  ROUTES.naughtySpins,
  ROUTES.snakesAndLovers,
  ROUTES.spotifyPlaque,
  ROUTES.stringFrame,
  ROUTES.timelessTreasure,
  ROUTES.timeCapsule,
  ROUTES.twentyFourReasons,
  ROUTES.relationshipCalendar,
  ROUTES.gifts,
  ROUTES.storefront,
  ROUTES.pricing,
  ROUTES.about,
  ROUTES.blog,
  ROUTES.terms,
  ROUTES.privacy,
  ROUTES.refund,
  ROUTES.login,
  ROUTES.register,
  ROUTES.verifyEmail,
  ROUTES.forgotPassword,
] as const;

export const AUTH_ROUTES = [
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
] as const;

export const PROTECTED_ROUTE_PREFIXES = [
  "/dashboard",
  "/admin",
  "/checkout",
  "/gifts/orders",
  "/gifts/wishlist",
] as const;
