export const ROUTES = {
  home: "/",
  experiences: "/experiences",
  games: "/games",
  scrapbook: "/experiences/scrapbook",
  scrapbookBuild: "/scrapbook/build",
  memoryJar: "/memory-jar",
  memoryJarBuild: "/memory-jar/build",
  memoryPages: "/experiences/memory-pages",
  memoryPagesBuild: "/memory-pages/build",
  constellation: "/constellation",
  constellationBuild: "/constellation/build",
  memoryCity: "/memory-city",
  memoryCityBuild: "/memory-city/build",
  chocolateBouquet: "/chocolate-bouquet",
  chocolateBouquetBuild: "/chocolate-bouquet/build",
  memoryLantern: "/memory-lantern",
  memoryLanternBuild: "/memory-lantern/build",
  ourPlaces: "/our-places",
  ludo: "/games/ludo",
  ludoBuild: "/ludo/build",
  countdown: "/countdown",
  countdownBuild: "/countdown/build",
  proposal: "/proposal",
  proposalBuild: "/proposal/build",
  dateAsk: "/date-ask",
  dateAskBuild: "/date-ask/build",
  redZone: "/red-zone",
  desireDeck: "/desire-deck",
  desireDeckBuild: "/desire-deck/build",
  desireMatcher: "/desire-matcher",
  desireMatcherBuild: "/desire-matcher/build",
  desireMatcherResults: "/desire-matcher/results",
  diceOfDesire: "/dice-of-desire",
  diceOfDesireBuild: "/dice-of-desire/build",
  loveCoupons: "/love-coupons",
  loveCouponsBuild: "/love-coupons/build",
  loveCouponsRedemptions: "/love-coupons/redemptions",
  naughtySpins: "/naughty-spins",
  naughtySpinsBuild: "/naughty-spins/build",
  snakesAndLovers: "/snakes-and-lovers",
  snakesAndLoversBuild: "/snakes-and-lovers/build",
  spotifyPlaque: "/spotify-plaque",
  spotifyPlaqueBuild: "/spotify-plaque/build",
  stringFrame: "/string-frame",
  stringFrameBuild: "/string-frame/build",
  timelessTreasure: "/timeless-treasure",
  timelessTreasureBuild: "/timeless-treasure/build",
  timeCapsule: "/time-capsule",
  timeCapsuleBuild: "/time-capsule/build",
  gifts: "/gifts",
  giftOrders: "/gifts/orders",
  giftWishlist: "/gifts/wishlist",
  storefront: "/shop",
  checkout: "/checkout",
  pricing: "/pricing",
  about: "/about",
  blog: "/blog",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  settings: "/dashboard/settings",
  shop: "/dashboard/shop",
  shopProducts: "/dashboard/shop/products",
  shopProductNew: "/dashboard/shop/products/new",
  shopOrders: "/dashboard/shop/orders",
  shopSettings: "/dashboard/shop/settings",
  admin: "/admin",
} as const;

// Marketing/demo surfaces anyone can see. Builder routes (`/*/build`) are
// intentionally NOT here — customising anything requires login, enforced in
// proxy.ts via isBuilderPath().
export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.experiences,
  ROUTES.games,
  ROUTES.scrapbook,
  ROUTES.memoryJar,
  ROUTES.memoryPages,
  ROUTES.constellation,
  ROUTES.memoryCity,
  ROUTES.chocolateBouquet,
  ROUTES.memoryLantern,
  ROUTES.ourPlaces,
  ROUTES.ludo,
  ROUTES.countdown,
  ROUTES.proposal,
  ROUTES.dateAsk,
  ROUTES.redZone,
  ROUTES.desireDeck,
  ROUTES.desireMatcher,
  ROUTES.diceOfDesire,
  ROUTES.loveCoupons,
  ROUTES.naughtySpins,
  ROUTES.snakesAndLovers,
  ROUTES.spotifyPlaque,
  ROUTES.stringFrame,
  ROUTES.timelessTreasure,
  ROUTES.timeCapsule,
  ROUTES.gifts,
  ROUTES.storefront,
  ROUTES.pricing,
  ROUTES.about,
  ROUTES.blog,
  ROUTES.login,
  ROUTES.register,
  ROUTES.verifyEmail,
  ROUTES.forgotPassword,
] as const;

export const AUTH_ROUTES = [
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
] as const;

export const PROTECTED_ROUTE_PREFIXES = [
  "/dashboard",
  "/admin",
  "/checkout",
  "/gifts/orders",
  "/gifts/wishlist",
] as const;
